version: "3.8"

services:
  app:
    image: brandietls/sample-app:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "5f4qza.h.filess.io"
      DB_USER: "C270 DevOps_searchten"
      DB_PASSWORD: "9a592585756f756e1d86f580ac6e7cfb69f2607a"
      DB_PORT: "3307"
      DB_NAME: "C270 DevOps_searchten"

    volumes:
      - uploads-data:/app/uploads
      - images-db:/app/uploads/images.txt
    networks:
      - appnet
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
networks:
  appnet:

volumes:
  mysql-data:
  uploads-data:
  images-db:



